### ISSUE TITLE
Self signed certificate not working (My fault?)

### ISSUE THREAD

**Issue by TerminatorNL** [sfackler/rust-native-tls#101]
Hello there, I'm new to rust, and I keep getting stumbled by this.

I have a self-signed certificate, but I can't seem to use it.
I tried using:

```
let cert = Certificate::from_pem(&read_cert_file).unwrap();
let mut connector = TlsConnector::builder().unwrap();
connector.add_root_certificate(cert).unwrap();
let connection = connector.build().unwrap().connect("127.0.0.1", TcpStream::connect("127.0.0.1:8443").unwrap());
        match connection {
            Ok(stream) => {
                match acceptor_server.accept(stream) {
                    Ok(mut stream) => {
                        println!("Connection was successful!");
                    },
                    Err(_) => {
                        /* Connection failed */
                        println!("Connection failed");
                    }
                }
            },
            Err(e) => {
                println!("Error: {}",e);
            }
        }
```

This always returns this:
```
Error: The OpenSSL library reported an error: The OpenSSL library reported an error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1230:
```

Am I doing something wrong here?

The server it connects to works like a charm with browsers, although I have to add a security exception (which makes sense) but when the code above tries to connect it also shows an error and is only raised when the remote doesn't accept the certificate
```
Connection with 127.0.0.1 failed, reason: ErrorStack([Error { code: 336151570, library: "SSL routines", function: "ssl3_read_bytes", reason: "sslv3 alert bad certificate", file: "ssl/record/rec_layer_s3.c", line: 1407, data: "SSL alert number 42" }])
```

I'm fine with sharing my private and public keys, as they are for testing purposes only right now, and will be swapped out later.

Thanks in advance.

**Comment by sfackler** [comment]
That should work - are you sure that the cert is the correct root for your server?

**Comment by TerminatorNL** [comment]
The server uses the identity.pfx (generated from private.key and cert.crt)
[server-certs.zip](https://github.com/sfackler/rust-native-tls/files/2163758/server-certs.zip)

The client imports this certificate (line 3)
[imported-cert-for-client.zip](https://github.com/sfackler/rust-native-tls/files/2163760/imported-cert-for-client.zip)

**Comment by TerminatorNL** [comment]
The password to that identity.pfx is `test`, by the way.

I may be doing something stupid here, but I am not sure what.

**Comment by TerminatorNL** [comment]
Issue unresolved, used workaround. (Obtain actual certificate)
