### ISSUE TITLE
why was the backend module removed?

### ISSUE THREAD

**Issue by sbditto85** [sfackler/rust-native-tls#103]
I was updating tokio_tls so i could update requwest to use 0.2 and some of the tests for tokio_tls use the backend module. Why was it removed? Seems i'll need to replicate it for the tokio_tls test, though I'm not sure because I'm still new.

**Comment by sfackler** [comment]
Removing it makes the openssl/security-framework/schannel libraries private dependencies so we can upgrade them as needed without a breaking change.

What do you specifically need to do that requires downcasting to the underlying types?

**Comment by sbditto85** [comment]
Its just the tests in tokio_tls ... im guessing I'll just have to import them into that project if I submit a PR.

Thanks!

**Comment by jethrogb** [comment]
@sfackler would you be open to supporting an API like https://docs.rs/reqwest/0.10.7/reqwest/struct.ClientBuilder.html#method.use_preconfigured_tls ? This allows users to set advanced options when necessary without breaking the public API on upgrades.

**Comment by sfackler** [comment]
That just defers a build-time failure to a run time failure.

**Comment by jethrogb** [comment]
I think these are the options:

1. Commit to wrapping all possible TLS backend configuration options.
    * How would this work when different backends support different things?
2. Support only a subset of TLS configuration options
    * This forces people to not use native-tls or use a fork of native-tls.
3. Make the backend part of the public API.
    * You would be able to upgrade the backend with a major version bump of native-tls.
    * You could make a crate native-tls-backends that publicly depends on the backends (similar to the way it was in native-tls 0.1). native-tls would depend on that crate and wrap everything, except for the public backend part of the API, which is not exposed. If you want to bump a backend version you do a new (major) version bump of native-tls-backends and you can change to this version in native-tls. Users who want to depend on a backend directly can use native-tls-backends. If there's a major version bump to native-tls-backends, they would need to update their use of the backend to the new version anyway, so there's not a lot of extra effort needed for them to update to the new version.
    * You might be able to build a scheme similar to the previous point using Cargo features.
4. Abstract over TLS with traits instead of implementation forwarding
    * It's not clear to me that this is going to be possible with dynamic dispatch, which is probably what you want here so you don't have to make everything generic.
