### ISSUE TITLE
Using native-tls with an identity in the OS X Keychain

### ISSUE THREAD

**Issue by andrew-d** [sfackler/rust-native-tls#104]
Hi there!

I'd love to be able to use `native-tls` and be able to specify an `Identity` that's backed by the OS X keychain, so as to support client-certificate TLS without exporting the credential (and then be able to use `hyper-tls`, etc.). Currently, you can only create an `Identity` through the `from_pkcs12` method - what are your thoughts on adding a `IdentityExt` trait (or similar name) that exposes OS-specific functionality for the `Identity` structure?  Something literally as simple as:

```rust
impl IdentityExt for Identity {
  pub fn from_keychain(identity: security_framework::identity::SecIdentity) -> Result<Identity> {
    Identity {
      identity,
      ... // cert chain stuff here
    }
  }
}
```

I'd be happy to submit a PR implementing this if it's something that sounds reasonable!

**Comment by sfackler** [comment]
This library is focused on providing a platform independent interface. If you want to specifically work with the OSX keychain, why not use security-framework directly?

**Comment by andrew-d** [comment]
So, I actually have a `Connect` implementation for hyper that uses `security-framework` directly, but it involves essentially copying 300+ lines of code from `hyper-tls` / `native-tls` to get the same behavior.  Specifically:

- I need to copy [`MaybeHttpsStream`](https://github.com/hyperium/hyper-tls/blob/master/src/stream.rs#L10) from `hyper-tls`, since it assumes that it's using `native-tls`, and I want to support both HTTP and HTTPS.  This applies to the other support/wrapper structs like `HttpsConnecting`, `TlsStream`, `Handshaking`, etc.)
- I needed to copy most of the `connect` method from `TlsConnector` in `native-tls` along with the supporting methods (e.g. to set the min. TLS version).

Ideally, I could avoid all the duplication and associated incompatibility with other crates that use `hyper-tls` if I can just create the `native-tls` `Identity` object with right identity 😃

**Comment by sfackler** [comment]
Again, 0.2 explicitly avoids exposing the internal implementations directly. I don't think not wanting to copy 300 lines of code for a use case that's tangentially related to native-tls's goal is really sufficient motivation to change that decision.
