### ISSUE TITLE
TlsConnector adds certificate chain from PKCS12 identity in reverse order

### ISSUE THREAD

**Issue by dremon** [sfackler/rust-native-tls#110]
Using native-tls 0.2.1 on Linux (openssl).

When building TlsConnector with pkcs12 identity which contains 3 certificates: [leaf, intermediate, root] the intermediate and root certificates are sent to the server peer in reverse order [leaf, root, intermediate] resulting in handshake errors (in particular the javax.net.ssl.SSLException: subject/issuer name chaining check failed).

**Comment by sfackler** [comment]
What order are the certificates stored in the PKCS12 file?

**Comment by dremon** [comment]
> #111 should fix this - could you try it out to confirm?

I think it's only implemented for TlsAcceptor in this PR, should be also changed for TlsConnector. When I change it manually it works, yes.

**Comment by sfackler** [comment]
Great! I'll cut a release with the fix this morning.
