### ISSUE TITLE
BoringSSL implementation

### ISSUE THREAD

**Issue by fabricedesre** [sfackler/rust-native-tls#112]
How likely is it to see a BoringSSL (https://boringssl.googlesource.com/boringssl/) implementation be accepted? OpenSSL is supported on the same platforms, but we end up with an additional native dependency which is not idea on some resource limited embedded devices.

**Comment by sfackler** [comment]
Someone would need to make sufficiently fully featured bindings to BoringSSL first.

**Comment by sfackler** [comment]
> Although BoringSSL is an open source project, it is not intended for general use, as OpenSSL is. We don't recommend that third parties depend upon it. Doing so is likely to be frustrating because there are no guarantees of API or ABI stability.

**Comment by fabricedesre** [comment]
Does that mean that you would not take BoringSSL support in this crate?

**Comment by sfackler** [comment]
I'd probably want a Google person maintaining the support since they're the only people that are actually intended to be consuming BoringSSL AFAIKT.

**Comment by vlovich** [comment]
https://github.com/google/mundane
