### ISSUE TITLE
"cert already in hash table" error could not be ignored

### ISSUE THREAD

**Issue by glebpom** [sfackler/rust-native-tls#115]
Hi,

Some systems don't have root certificates installed, so that it may be a good idea to provide bunded root CA's as a part of the binary. But, on systems with certificates installed, it may lead to the "cert already in hash table" error. It seems like there is no way to just ignore this error.

**Comment by sfackler** [comment]
Ah yeah, we should ignore that error in particular when adding certs to the store.
