### ISSUE TITLE
Does not compile on macOS Sierra

### ISSUE THREAD

**Issue by fenhl** [sfackler/rust-native-tls#119]
The crate has recently stopped compiling on macOS 10.12.6 Sierra. The compiler produces 78 errors, each with the following note:

> note: Perhaps two different versions of crate `core_foundation_sys` are being used?

I believe the issue appeared with today's [security-framework-sys](https://crates.io/crates/security-framework-sys) release.

**Comment by sfackler** [comment]
This seems like something that should be filed on security-framework?

**Comment by kornelski** [comment]
Yes, that's a fallout from update of core-foundation-sys.

**Comment by code-ape** [comment]
I also have had multiple projects breaking as a result of this as well.

@sfackler, to your point, this appears to be a consequence of the current package layout for `rust-security-framework`. It appears this package has been designed to assume releases are "fully coordinated" but right now `security-framework` is at `0.2.2` while `security-framework-sys` has had breaking changed as a patch version updated (`0.2.4`). I just opened a ticket with `rust-security-framework` with possible solutions (https://github.com/kornelski/rust-security-framework/issues/78). Let me know if you need anything else to get this resolved soon :)

**Comment by kornelski** [comment]
That's now resolved by publishing a matching version of `security-framework`.
