### ISSUE TITLE
Possibility to use identity acquired from system certificate store 

### ISSUE THREAD

**Issue by dremon** [sfackler/rust-native-tls#122]
Private key chains stored in Windows certificate store are often marked as non-exportable and cannot be acquired into the application, but they still have to be used as an identities during TLS handshake.

Would it be a huge effort to implement this in native-tls? I'd imagine for example `TlsConnectorBuilder` having an extra method like `system_identity(true)` which will assume whatever default keystore from the system.
On openssl-based systems that would probably do nothing.

**Comment by sfackler** [comment]
I'd recommend using the `schannel` crate directly if you want to do Windows-specific stuff.

**Comment by dremon** [comment]
The problem is that it won't be integrated into native-tls and, as a consequence, into tokio-tls and the whole tokio thing. A lot should be reimplemented, and the code must be kept platform-independent.

I can do this in a fork and later submit a PR for review, if that kind of functionality would be accepted as a feature.

**Comment by dremon** [comment]
Sorry, wasn't meant to close the issue.

**Comment by sfackler** [comment]
Someone can make `tokio-schannel`.
