### ISSUE TITLE
Unable to specify a private key / certificate chain for mutual TLS

### ISSUE THREAD

**Issue by richardwhiuk** [sfackler/rust-native-tls#125]
In native-tls 0.1, it was possible to do this, as follows:

```
let mut ssl =
            openssl::ssl::SslConnectorBuilder::new(openssl::ssl::SslMethod::tls()).unwrap();

 // Server authentication 
 ssl.set_ca_file(ca_certificate.clone()).unwrap(); 
  
 // Client authentication 
 ssl.set_private_key_file(client_key.clone(), openssl::x509::X509_FILETYPE_PEM) 
     .unwrap(); 
 ssl.set_certificate_chain_file(client_certificate.clone()) 
     .unwrap(); 
 ssl.check_private_key().unwrap(); 
  
 let builder: native_tls::TlsConnectorBuilder = 
     native_tls::backend::openssl::TlsConnectorBuilderExt::from_openssl(ssl); 
```

It's not possible to do this in native tls 0.2, as `TlsConnectorBuilderExt` has been removed, and `TlsConnectorBuilder` doesn't implement this functionality natively.

**Comment by sfackler** [comment]
If you only need to support OpenSSL, then it may be easier to use OpenSSL directly.

You can specify an identity for mutual TLS via https://docs.rs/native-tls/0.2.2/native_tls/struct.TlsConnectorBuilder.html#method.identity

**Comment by richardwhiuk** [comment]
The former isn't possible because `hyper-tls` only takes a `native_tls::TlsConnectorBuilder`.

I think for the later to work, we'd need a bunch of enhancements to `native_tls`. Currently I believe it's impossible to ignore default root CAs, which looks tricky to implement for the schannel based API. We'd probably also need some enhancements to support PEM based keys and certificates, but that's more practical.

**Comment by richardwhiuk** [comment]
Note, I think this change is probably right for the crate (and will allow us to lift the current linux only restriction on our current API).

**Comment by sfackler** [comment]
https://docs.rs/hyper-openssl/0.7.1/hyper_openssl/

**Comment by richardwhiuk** [comment]
Ah, interesting - yes that should provide a path forward.

**Comment by richardwhiuk** [comment]
Happy to close this. Long term, I do want to move swagger to use hyper-nativetls for cross platform support, though supporting many different options is also a possibility.

**Comment by AsadMGradex** [comment]
Hi there, I have been following some breadcrumbs to simply compile a server that I generated using swagger. I was having issues with the openssl library but after finally getting that to work I get the error:
  --> ..\swagger-0.12.1\src\connector.rs:41:34
   |
41 |             native_tls::backend::openssl::TlsConnectorBuilderExt::from_openssl(ssl);
   |                                  ^^^^^^^ could not find `openssl` in `backend`

error[E0433]: failed to resolve: could not find `openssl` in `backend`
  --> ...\swagger-0.12.1\src\connector.rs:85:34
   |
85 |             native_tls::backend::openssl::TlsConnectorBuilderExt::from_openssl(ssl);
   |                                  ^^^^^^^ could not find `openssl` in `backend`


I think this is the same issue @richardwhiuk was describing. Sorry in advance but I am new to RUST. I am using versions:
swagger = "0.12.1"
native-tls = {version = "0.1.4", optional = true}
openssl = {version = "0.9.24", optional = true}

trying to update the openssl version to a more recent version throws a 10x more errors so I am kind of stuck here. Any ideas on how to fix this issue?

**Comment by sfackler** [comment]
The backend::openssl module only exists if you're using a non-Windows/non-macOS system.

**Comment by AsadMGradex** [comment]
Is why I am getting the error as I'm developing on windows, what would be the workaround for this if using windows

**Comment by sfackler** [comment]
I believe your workaround would be to upgrade to 0.2 which has support for client certificates.

**Comment by AsadMGradex** [comment]
which crate needs to be upgraded to 0.2? I have tried upgrading all of them individually to higher crate/latest one for that individual crate but that throws more errors or the same ones. Unless I have to upgrade them all as they do depend on each other. Seems like swagger is outdated, the generation of a new server or client has build issues by default..

**Comment by sfackler** [comment]
native-tls

**Comment by AsadMGradex** [comment]
changed it to this: **native-tls = {version = "0.2", optional = true}**

Compiling native-tls v0.2.3
Compiling swagger v0.12.1
error[E0433]: failed to resolve: could not find `openssl` in `backend`
  --> C:\Users\amahmud\.cargo\registry\src\github.com-1ecc6299db9ec823\swagger-0.12.1\src\connector.rs:41:34
   |
41 |             native_tls::backend::openssl::TlsConnectorBuilderExt::from_openssl(ssl);
   |                                  ^^^^^^^ could not find `openssl` in `backend`

error[E0433]: failed to resolve: could not find `openssl` in `backend`
  --> C:\Users\amahmud\.cargo\registry\src\github.com-1ecc6299db9ec823\swagger-0.12.1\src\connector.rs:85:34
   |
85 |             native_tls::backend::openssl::TlsConnectorBuilderExt::from_openssl(ssl);
   |                                  ^^^^^^^ could not find `openssl` in `backend`


So had no effect it seems

**Comment by sfackler** [comment]
It looks like you will need to get swagger to update its dependency.

**Comment by AsadMGradex** [comment]
Okay so I decided to look through @richardwhiuk trail in regards to this issue.
Originally this solved the issue: https://github.com/sfackler/rust-native-tls/pull/37
Which was taken out in: https://github.com/sfackler/rust-native-tls/commit/bb10ac55c3e8f1b7cb82d7ae0a305bba58d0dd52#diff-c67038c29bc9227b0ac84a64061cbd31 

According to Richard's and @sfackler 's dialogue it looks like using the **hyper-openssl** crate will let you bypass the issue originally highlighted in Richard's original comment.

However that's for SslConnector NOT **SslAcceptor**. According to the documentation the connector is for the client side TLS connections whereas the acceptor is for the server side connections. So although the hyper-openssl crate solves the issue for the connector you run into the same issue with the SslAcceptor. 

I have no way of 'connecting' the **open_ssl** crates' **SslAcceptor** with the **native_tls** crate's **TlsAcceptor**.

@sfackler , any thoughts?

**Comment by sfackler** [comment]
I don't understand what you mean by connecting SslAcceptor with TlsAcceptor. What is the specific thing you are trying to do?

hyper-openssl implements a hyper trait specific to client side connections. There is no such trait for server side connections.

**Comment by AsadMGradex** [comment]
So this was the code generated by openapigenerator:
`    
    let mut ssl = SslAcceptorBuilder::mozilla_intermediate_raw(SslMethod::tls())?;

    // Server authentication
    ssl.set_private_key_file("examples/server-key.pem", X509_FILETYPE_PEM)?;
    ssl.set_certificate_chain_file("examples/server-chain.pem")?;
    ssl.check_private_key()?;

    let service_fn =
        openapi_client::server::context::NewAddContext::<_, EmptyContext>::new(
            AllowAllAuthenticator::new(
                server_lib::NewService::new(),
                "cosmo"
            )
        );

        let builder: native_tls::TlsAcceptorBuilder = native_tls::backend::openssl::TlsAcceptorBuilderExt::from_openssl(ssl);
        let tls_acceptor = builder.build().expect("Failed to build TLS acceptor");
        tokio_proto::TcpServer::new(tokio_tls::proto::Server::new(Http::new(), tls_acceptor), addr).serve(service_fn);
`
So it is essentially the same Richard's code but for the acceptor (server side). 
The examples I have seen seem to completely disregard native_tls for establishing the server and use tokio_openssl instead but if that is the case then what is the point of the TlsAcceptor in the first place?

**Comment by sfackler** [comment]
If that code is directly interfacing with OpenSSL, is seems like it should just use the openssl crate rather than native-tls.

**Comment by AsadMGradex** [comment]
The only interfacing it does with OpenSSL is when it creates the SslAcceptor which it then passes to a native tls function that no longer exists. Am I to assume there's no way of generating a server by first creating an ssl acceptor, setting its information and then passing it to the native-tls' TLSAcceptor? So native-tls will work with open-ssl when using the TLSConnector but not the TLSAcceptor?

Openapigenerator couldn't keep up with the changes so It has generated this broken code. I just want to confirm if there is a workaround for the server side like you recommended before for the client side (using hyper-openssl), if not then I'll have to change a lot of the code that got generated.
