### ISSUE TITLE
Update security-framework to 0.3.0

### ISSUE THREAD

**Issue by kpcyrd** [sfackler/rust-native-tls#126]
hello!

I noticed the security-framework and security-framework-sys is outdated. :)

Would you mind updating the dependency? (don't have an apple development environment myself) Thanks!

**Comment by sfackler** [comment]
#124

**Comment by sfackler** [comment]
Done

**Comment by kpcyrd** [comment]
Awesome! Are there any plans to publish an update?

**Comment by sfackler** [comment]
Done!
