### ISSUE TITLE
Allow `Identity`s to be cloned

### ISSUE THREAD

**Issue by bruceg** [sfackler/rust-native-tls#138]
The `Identity` struct, as consumed by `TlsConnectorBuilder::identity`, is not clonable. Due to this, if the same identity pair needs to be used in more than one place, it must be parsed from source data in each place, requiring error handling at each point.

For comparison, the `Certificate`, consumed by `TlsConnectorBuilder::add_root_certificate` for example, is clonable.

Can `Identity` be made clonable?

**Comment by sfackler** [comment]
It'll require some work on the OpenSSL side.

**Comment by bruceg** [comment]
Thanks!
