### ISSUE TITLE
native-tls tests fail on macOS Catalina

### ISSUE THREAD

**Issue by stepancheg** [sfackler/rust-native-tls#151]
```
$ cargo test
...
---- test::tests::server stdout ----
thread 'test::tests::server' panicked at 'Failure(Error { code: -67843, message: "The certificate was not trusted." })', src/test.rs:80:26


failures:
    test::tests::peer_certificate
    test::tests::server
    test::tests::server_pem
    test::tests::server_tls11_only
    test::tests::shutdown
    test::tests::tls_server_end_point

test result: FAILED. 7 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by sfackler** [comment]
We just need to regenerate the test certificate in accordance with Catalina's new requirements: https://support.apple.com/en-us/HT210176.

**Comment by stepancheg** [comment]
Also, if native-tls can depend on the presence of `openssl` binary, this file can be used to generate everything on the fly: https://github.com/stepancheg/rust-tls-api/blob/master/api-test/src/openssl_test_key_gen.rs (this is copied from tokio-tls and made self-contained.)

**Comment by pimeys** [comment]
We've been hitting the same issue in Tiberius, where mac users are having the same error. Is there a workaround to fix this already?

**Comment by sfackler** [comment]
You need to regenerate your certificates in accordance with Catalina's new requirements: https://support.apple.com/en-us/HT210176

**Comment by colinre** [comment]
Same issue now on Sonoma 14.2.1
