### ISSUE TITLE
danger_accept_invalid_certs behavior

### ISSUE THREAD

**Issue by shriphani** [sfackler/rust-native-tls#158]
Hi,

Thank you for your work on this library. I have this situation where I don't quite care about identity (identity is established in other parts of my system) and thus I want servers to be able to use self-signed certs. I see that `danger_accept_invalid_certs` allows me to do that.

My question is what happens after I establish a connection using `danger_accept_invalid_certs` - is the channel still secure - i.e. it isn't like the server and client are talking over plaintext.

Thank you,
Shriphani

**Comment by sfackler** [comment]
If you enable `danger_accept_invalid_certs`, you lose guarantees about the identity of the server you're talking to. If you have already established that externally, then that wouldn't be a problem (in theory). The connection will still be encrypted the same way regardless of that setting though.

**Comment by shriphani** [comment]
Thank you very much for your response, exactly what I wanted - hope you are in good health through this COVID-19 season.

**Comment by shriphani** [comment]
I have one more question about this - if the server uses invalid certs (i.e. some key clearly not from the cert being used as opposed to a self-signed cert), would this function call allow the session to be established?

**Comment by sfackler** [comment]
I don't know, but that seems kind of irrelevant if you don't care what identity the server is providing.

**Comment by cypheratheist** [comment]
@shriphani The server needs the right private key.  The client will send the premaster secret encrypted with the server public key, extracted from the certificate.  The server needs to be able to decrypt this to be able to establish the session key.  I believe the `danger_accept_invalid_certs()` simply refers to CA validation, not the actual key exchange protocol.

@sfackler That's not entirely true.  Once you extracted the certificate from the stream you can do custom validation (for instance you may have obtained a copy of the server's certificate through a different trusted channel, and you simply compare the TLS channel's copy against the one you keep stored), but you still want the TLS layer to have ensured that the server is the holder of the private key.

**Comment by shriphani** [comment]
Thanks @cypheratheist - sorry I forgot to close this issue; `danger_accept_invalid_certs` works well for my use-case.
