### ISSUE TITLE
what policy about other common crypto functions?

### ISSUE THREAD

**Issue by davemilter** [sfackler/rust-native-tls#170]
security-framework crate and OpenSSL (via the openssl crate) have also such common functions:

- sha1
- symmetric encryption
- secure random

is this ok to add common API for them into native-tls (may be behind feature flags),
or it should be separate crate ?

**Comment by sfackler** [comment]
I do think something like this should exist, but my preference would be to keep this crate focused on TLS specifically, and introduce a "native-crypto" crate for other bits like that.

**Comment by davemilter** [comment]
Thanks for answer.
