### ISSUE TITLE
openssl_probe::init_ssl_cert_env_vars

### ISSUE THREAD

**Issue by vkandy** [sfackler/rust-native-tls#180]
`openssl_probe::init_ssl_cert_env_vars()` now returns a `bool` which fails to compile at this line:

https://github.com/sfackler/rust-native-tls/blob/master/src/imp/openssl.rs#L94

```
   |
94 |     ONCE.call_once(|| openssl_probe::init_ssl_cert_env_vars());
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `()`, found `bool`
```

**Comment by sfackler** [comment]
That is a break in openssl_probe, and the release has been yanked.
