### ISSUE TITLE
Is it possible to add client certificate?

### ISSUE THREAD

**Issue by GopherJ** [sfackler/rust-native-tls#183]
Hi, is it possible to add ClientConfig like rustls? (cert, private key)

I just found `add_root_certificate` in `TlsConnector`
https://docs.rs/native-tls/0.2.4/native_tls/struct.TlsConnectorBuilder.html#method.add_root_certificate

**Comment by sfackler** [comment]
https://docs.rs/native-tls/0.2.4/native_tls/struct.TlsConnectorBuilder.html#method.identity

**Comment by GopherJ** [comment]
@sfackler Hi, thanks for your reply, I had a look and understood better, the naming of `Identity` makes me confused and why it needs `password`?

**Comment by sfackler** [comment]
An `Identity` is a certificate and private key combined. It can currently only be constructed from a PKCS#12 archive, which requires a password to encrypt the key.

**Comment by GopherJ** [comment]
ok I understood, though it's pretty strange that x509 is not supported. thanks for your patience
