### ISSUE TITLE
Error in macOS 10.12.2 for p12 cert which works in Win/Linux

### ISSUE THREAD

**Issue by mattdw** [sfackler/rust-native-tls#19]
Hi,

I'm using this with great success on Win and Linux. So, thanks! Unfortunately though, on macOS Sierra, the p12 identity file I've created with the documented openssl command just gives me:

```rust
Tls(Error { code: -25264, message: "MAC verification failed during PKCS12 import (wrong password?)" })
```

I tried recreating the .p12 using the current macOS openssl (0.9.8zh), just in case it was a compatibility problem, but while the file hashes differed, I got exactly the same error message.

I'm using a self-signed cert, no intermediate chain, and an empty password. I'm using it via hyper-native-tls and my code looks like:

```rust
let ssl = match NativeTlsServer::new("devkey/certificate.pfx", "") {
    Ok(server) => server,
    Err(e) => { println!("{:?}", e); panic!("Error loading ssl cert") }
};
```

My lock file says hyper-native-tls 0.2.1 and native-tls 0.1.1. Let me know if I can provide you with any more info, or run any further tests for you – I can test on all platforms.

Thanks,
Matt.

**Comment by sfackler** [comment]
That's weird. Can OSX's keychain utility open it?

**Comment by mattdw** [comment]
Ah, interesting, keychain can't open even the version created with the local macOS openssl. When I try to "View Certificates" in the Add Certificates panel:

> **An error has occurred. Unable to display information about the selected item.**  
> This item contains information which is too large or in a format that cannot be displayed.

And when I try to "Add", I get an 'invalid password' error.

I just generated a new key/cert pair, and a .pfx from the following commands, and the new .pfx also fails to be opened in keychain.

```bash
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -nodes -subj '/CN=localhost'
openssl pkcs12 -export -out identity.pfx -inkey key.pem -in cert.pem
```

I can upload the files if you want, although it's looking like this probably isn't your problem! Any variations on openssl commands I should try?

Thanks again!

**Comment by sfackler** [comment]
Weird! Not sure what would be going on, honestly.
