### ISSUE TITLE
Make rust-native-tls obey the system openssl.cnf file

### ISSUE THREAD

**Issue by karnal222** [sfackler/rust-native-tls#195]
Usually you can set global variables for openssl via the openssl.cnf file. I'm using a program* which makes use of native-tls but does not seem to obey the config file. Is there any way to change that or setting parameters like ciphers or protocol without recompiling the program or library?

* https://github.com/vi/websocat

**Comment by sfackler** [comment]
I'm not familiar with how OpenSSL looks for configuration files, but one possibility is that you're not linking to the system OpenSSL installation but instead some other one (maybe vendored) that has a different directory configured.
