### ISSUE TITLE
How to retrieve the TcpStream back on failure

### ISSUE THREAD

**Issue by vasishath** [sfackler/rust-native-tls#198]
Hello,
I am using native_tls for an app and everything is working fine except for one small issue. I have registered multiple TcpStreams in mio poll and want to retrieve the stream back in case the handshake fails so that I can de-register it before the underlying socket closes. I have currently implemented Drop trait for the stream but since it needs a mutable reference to the poll registry, I have to resort to use raw pointer and unsafe code. Is there any better way to do this ?

**Comment by zybmajia1** [comment]
hello，I have a truble in rust-tls::Acceptor(mio::TcpStream)，can you help me?
rust-tls::Acceptor(mio::TcpStream) ret:
err: the handshake process was interrupted
rust-tls::Acceptor(net::TcpStream)' ret ok。
I dont know why.

**Comment by vasishath** [comment]
> Hello, I am using native_tls for an app and everything is working fine except for one small issue. I have registered multiple TcpStreams in mio poll and want to retrieve the stream back in case the handshake fails so that I can de-register it before the underlying socket closes. I have currently implemented Drop trait for the stream but since it needs a mutable reference to the poll registry, I have to resort to use raw pointer and unsafe code. Is there any better way to do this ?

So I have worked around this by keeping an Rc reference to the mio poll registry and then deregistering it every time it is dropped.

**Comment by vasishath** [comment]
> hello，I have a truble in rust-tls::Acceptor(mio::TcpStream)，can you help me? rust-tls::Acceptor(mio::TcpStream) ret: err: the handshake process was interrupted rust-tls::Acceptor(net::TcpStream)' ret ok。 I dont know why.

Can you post more code?

**Comment by zybmajia1** [comment]
let ret = listener.accept();//mio::TcpListener
        if let Result::Err(e) = ret {
            return None;
        }

        let (mut client, addr) = ret.unwrap();//mio::TcpStream
        let acc = tls_acceptor.accept(client);
        if let Err(e) = acc {
            log_error!("wss连接失败:{},{:?}", &e, e);
            return None;
        }

**Comment by zybmajia1** [comment]
this is my code, it work bad:
i have not finish yet. it return  when use  "tls_acceptor.accept(client);"
errinfo is 'the handshake process was interrupted'

**Comment by sfackler** [comment]
You probably shouldn't use mio directly. If you want to work with nonblocking IO, use tokio and tokio-native-tls.

**Comment by zybmajia1** [comment]
> 

Oh, thank you . Realy?  It will have a Huge change to my project.

**Comment by zybmajia1** [comment]
> You probably shouldn't use mio directly. If you want to work with nonblocking IO, use tokio and tokio-native-tls.

I realy not want to use tokio . There any other thing work?
haha，I want tcp,http,websocket and wss consolidate.
Tcp and websocket are work and wss will be bad.
the worst is nginx, but i have no choice.

**Comment by sfackler** [comment]
If you really want to do this manually, you'd get the `MidHandshakeTlsStream` from the `HandshakeError` and get the `TcpStream` from that.

**Comment by zybmajia1** [comment]
> If you really want to do this manually, you'd get the `MidHandshakeTlsStream` from the `HandshakeError` and get the `TcpStream` from that.

Ah,HandshakeError only has get_mut and get_ref.  
And the accept need move . 
It looks not work.

**Comment by zybmajia1** [comment]
if let native_tls::HandshakeError::WouldBlock(m) = e{
                tls_acceptor.accept(*m.get_ref());              
            }

that is.

**Comment by zybmajia1** [comment]
> ```
>        if let native_tls::HandshakeError::WouldBlock(m) = e{
>             tls_acceptor.accept(*m.get_ref());              
>         }
> ```
> 
> that is.
oooh, bellow is right.
 tls_acceptor.accept(m.get_ref());

**Comment by zybmajia1** [comment]
Sorry i give up . It will use ref tcpstream. It`s change is huge, Need change many fields because of reference.
The rustls's acceptor is a new function. Params is &mut too. 
You are all ref tcpstream. And lifetime is terrible because of refrence.
It will be easy if tcpstream has copy trait.

Finaly nginx is good idea.
