### ISSUE TITLE
(OpenSSL) Server rejects client: "tlsv1 alert unknown ca"

### ISSUE THREAD

**Issue by bluejekyll** [sfackler/rust-native-tls#20]
I'm a little stuck. I've tried a million different things, but I keep getting this error on linux (using openssl 1.0.2 in Docker with debian:jessie-backports, and also fails in travis-ci).

rust-openssl: v0.9.7
native-tls: v0.1.1

The error is this: 

`Failure(Ssl(ErrorStack([Error { code: 336151576, library: "SSL routines", function: "SSL3_READ_BYTES", reason: "tlsv1 alert unknown ca" }])))`

I've tried a whole bunch of different things like:

```rust
let pkcs12 = native_tls::Pkcs12::from_der(&server_pkcs12_der, "mypassword").expect("Pkcs12::from_der");
    let mut tls = TlsAcceptor::builder(pkcs12).expect("build with pkcs12 failed");

    #[cfg(target_os = "linux")]
    {
      let mut openssl_builder = tls.builder_mut();
      let mut openssl_ctx_builder = openssl_builder.builder_mut();
      let mut mode = openssl::ssl::SslVerifyMode::empty();
      // mode.insert(SSL_VERIFY_PEER);
      // mode.insert(SSL_VERIFY_FAIL_IF_NO_PEER_CERT);

      openssl_ctx_builder.set_verify(mode);
      openssl_ctx_builder.set_default_verify_paths().unwrap();
      openssl_ctx_builder.cert_store_mut().set_default_paths().unwrap();
    }

    let tls = tls.build().expect("tls build failed");
```

but nothing seems to change this. Any tips? The default code on macOS (i.e. without that linux block) works without a problem. So I don't think is key format issues or anything. Full code is here:

https://github.com/bluejekyll/trust-dns/blob/dns_over_tls/client/src/tls/tls_stream.rs#L236

recent build failure for reference:

https://travis-ci.org/bluejekyll/trust-dns/jobs/200925570

**Comment by sfackler** [comment]
Does it work on OpenSSL without that configuration? Do you want to require client certificates?

**Comment by bluejekyll** [comment]
No, it doesn't work with or without that configuration. That was an example of some of the steps I've taken to try and workaround the issue. The error that I mentioned is coming from the server acceptor in the test (standard blocking version). From my understanding it is saying that it is a client validation error, which is why I started looking at different options for disabling validation on the server side.

Eventually I do want client-auth, but not right now.

The out-of-the-box setup works for macOS, just not linux. I am using a self-signed cert, the logic for that is a few lines up:

https://github.com/bluejekyll/trust-dns/blob/dns_over_tls/client/src/tls/tls_stream.rs#L251

**Comment by sfackler** [comment]
It looks like OpenSSL will verify client certificates sent to it even if they haven't been requested. Either not sending the client cert or configuring the server's trust root to include the client cert's CA should fix things.

**Comment by sfackler** [comment]
You can also disable certificate verification on the server side with `set_verify(SSL_VERIFY_NONE)`.

**Comment by bluejekyll** [comment]
Yeah. I tried that and am not sending a client cert. I'll make an isolated test case.

**Comment by bluejekyll** [comment]
Ok, thanks for the help earlier. I think I figured out what was going on, but haven't had a chance to fix it yet. The mac version of the TlsConnectorBuilderExt allows for certificate pinning, where-as I was trying to add the CA's dynamically. This led me to passing the wrong type of cert to the openssl version. #21 has a new test for the Connector. It's not ready, but I wanted to show you what I'm talking about. #21 is correct on Linux, but wrong on macOS, this was the inverse of the problem I was having on Linux and is an indication that I was using my certs wrong.

**Comment by bluejekyll** [comment]
Circling back around on this. I just pushed a solution to this issue in rust-openssl which will allow certs to be associated in the same way as I wanted to use them here.

https://github.com/sfackler/rust-openssl/pull/582

This can be closed with the solution being to use `SslContextBuilder::set_verify_cert_store()`, which matches the functionality of `TlsConnectorBuilderExt::anchor_certificates()` on macOS.

**Comment by sfackler** [comment]
Sweet, closing in favor of that!
