### ISSUE TITLE
Support for elliptic private keys possible?

### ISSUE THREAD

**Issue by DerAndereAndi** [sfackler/rust-native-tls#221]
HI everyone,

when using an identity pkcs8 key that uses an elliptic private key with the 1st line string

```
-----BEGIN EC PRIVATE KEY-----
```

instead of 

```
-----BEGIN PRIVATE KEY-----
```

then the library can't work with it. When modifying the 1st line to the later it works. Would it be possible to support this out of the box without requiring to modify this line?

That would be awesome. Thanks for the library and all the work it involves!
Andreas

**Comment by sfackler** [comment]
I believe that is SEC 1 formatted rather than PKCS#8. This SO post talks about the difference and how to convert between them: https://security.stackexchange.com/a/84331

**Comment by DerAndereAndi** [comment]
Very good point. Thank you!
