### ISSUE TITLE
The client and server cannot communicate, because they do not possess a common algorithm.

### ISSUE THREAD

**Issue by jacobtread** [sfackler/rust-native-tls#226]
I am trying to make a game server for a game that only uses SSLv3 the cipher suites it uses are TLS_RSA_WITH_RC4_128_MD5 and TLS_RSA_WITH_RC4_128_SHA I have enabled them in windows but I get the error message "The client and server cannot communicate, because they do not possess a common algorithm."

**Comment by jacobtread** [comment]
![image](https://user-images.githubusercontent.com/33708767/165998072-9682dcfc-c495-4bf9-a435-32bf86b93339.png)

**Comment by sfackler** [comment]
I am not familiar enough with Windows to say what else you would need to do, but it is not surprising to me that Windows has disabled SSLv3.

**Comment by jacobtread** [comment]
So are you saying my best bet would be to switch to linux?

**Comment by jacobtread** [comment]
So are you saying my best bet would be to switch to linux?

**Comment by sfackler** [comment]
I'm not sure what your best bet would be. SSLv3 has been deprecated for over a decade, and it may be difficult to find modern libraries that can easily be configured to continue supporting it.

**Comment by jacobtread** [comment]
Alright thank you for your help I managed to get it sslv3 working on the jvm after a decent bit of tweaking so I guess I'll just stick with that instead
