### ISSUE TITLE
Consider upgrading to tempfile = "3.4.0"

### ISSUE THREAD

**Issue by ge3224** [sfackler/rust-native-tls#251]
Github has issued [a low-risk advisory](https://github.com/advisories/GHSA-mc8h-8q98-g5hr) for  the version of `remove_dir_all` that is used by `tempfile` versions 3.0 and 3.1.0. `tempfile` [recently switched to](https://github.com/Stebalien/tempfile/commit/52dc0f9e053bba40a48e027e81f95d129790bfe2) `std::fs::remove_dir_all`.

**Comment by sfackler** [comment]
https://github.com/sfackler/rust-native-tls/pull/249#issuecomment-1445219493
