### ISSUE TITLE
RUSTSEC-2023-0018

### ISSUE THREAD

**Issue by RockyGitHub** [sfackler/rust-native-tls#252]
Cargo audit just recently came up with a new vulnerability, RUSTSEC-2023-0018.
```rust
Dependency tree:
remove_dir_all 0.5.3
└── tempfile 3.3.0
    └── native-tls 0.2.11
```
tempfile removes the dependency in 3.4.0, so it may be a simple update in dependency to fix this

**Comment by sfackler** [comment]
https://github.com/sfackler/rust-native-tls/issues/251
https://github.com/sfackler/rust-native-tls/pull/249
https://github.com/sfackler/rust-native-tls/pull/250
