### ISSUE TITLE
Please update openssl dependency.

### ISSUE THREAD

**Issue by SilenLoc** [sfackler/rust-native-tls#255]
https://github.com/sfackler/rust-native-tls/blob/8fa929d6c3fb7c7adfca9e0fdd6446f5dfb34f92/Cargo.toml#L31

The newest version has a fix that solves a security/safety problem.

See: 
https://rustsec.org/advisories/RUSTSEC-2023-0022
solved in
0.10.48

**Comment by sfackler** [comment]
`cargo update`.
