### ISSUE TITLE
TlsConnectorBuilder constructor

### ISSUE THREAD

**Issue by lapointexavier** [sfackler/rust-native-tls#266]
Hi,

I wanted to use the TLsConnectorBuilder to add a self signed certificate, and it appears that there's no default constructor for that struct. I know this is very minor, but I was wondering if either I didn't look properly, or if there was an opportunity to improve this api.

Currently I think I'd need to fill in all fields:
```rust
TlsConnectorBuilder {
  identity: None,
  min_protocol: None,
  ...
}.add_root_certificates(...).build()
```

And I'd like to write something similar to:
```rust
TlsConnectorBuilder::new().add_root_certificates(...).build()
```

I assume the default (either through `TlsConnectorBuilder::new()` or `impl Default for TlsConnectorBuilder`) would need to populate sensible values.

I'd be happy to contribute.

Thank you

**Comment by lapointexavier** [comment]
My apologies, just saw as test where TlsConnector::builder() is used.

**Comment by rust1248** [comment]
I stumbled upon this today, I think it should be documented on `TlsConnectorBuilder` (how to get one)
