### ISSUE TITLE
Is `&TlsStream: Read + Write` possible?

### ISSUE THREAD

**Issue by rMazeiks** [sfackler/rust-native-tls#276]
`TlsStream` implements Read and Write. However, `&TlsStream` doesn't, unlike `&std::net::TcpStream`.

Is it possible to implement these traits for references to `TlsStream` as well?

Use case: I need to share a TlsStream accross 2 threads. I want to read from it in one thread, and write to it in another. Unfortunately, this means that I have to use a Mutex to synchronize access, which leads to deadlock if the reading thread is blocking, waiting for data that won't come until the writing thread sends something.

[Related SO post](https://stackoverflow.com/q/76818542/22240348)

Thank you!

**Comment by sfackler** [comment]
It is not.

**Comment by rMazeiks** [comment]
Bit curious why, but I'll take your word for it :laughing: 

Thanks for the quick reply!
