### ISSUE TITLE
Is there any way to set cipher list?

### ISSUE THREAD

**Issue by IAkumaI** [sfackler/rust-native-tls#307]
Hello, I need to connect to some old server which I obviously cannot control. 
It gives me "dh key too small" error. I found the workaround: set SECLEVEL to 0 or 1, but cannot realize how to.

Found this https://github.com/sfackler/rust-openssl/issues/1328 but there is not way to `set_cipher_list` in native-tls.
`TlsConnector::builder()` does not have any suitable methods or at least something.

I'm using `reqwest` crate if it matters.

Could you help, please?

**Comment by sfackler** [comment]
There is no way to configure algorithms that are that exotically insecure.

**Comment by IAkumaI** [comment]
Ok, thanks for replying
