### ISSUE TITLE
Split some PKI types used by native-tls into separate crate

### ISSUE THREAD

**Issue by delta4chat** [sfackler/rust-native-tls#311]
Since some crates want to use some of struct types from native-tls, and they do not need TLS support, but these types are currently embedded in native-tls crate, so the corresponding TLS implementations are compiled/linked unnecessarily.

For example, types like `native_tls::Certificate`, `native_tls::Identity`, `native_tls::Protocol` can be bloated with unnecessary TLS specific implementations for libraries that don't involve TLS, such as certificate managers, which only need to access the certificate types of native-tls.

And these libraries cannot just copy the same struct on their own, because Rust Compiler recognizes them as separate and distinct types, so naturally they'll be wrong.

For native-tls, refer to [rustls-pki-types](https://docs.rs/rustls-pki-types) from rustls, which splits the PKI type into a separate crate and then adds it as a dependency in the rustls library. This way, other crates can just use the `rustls-pki-types` library while using the same type as rustls.

**Comment by sfackler** [comment]
> so the corresponding TLS implementations are compiled/linked unnecessarily.

The Certificate/Identity types are backed by those TLS implementation. How will this split avoid linking to OpenSSL/SChannel/Secure Transport?

**Comment by delta4chat** [comment]
My mistake... Because `native_tls::Certificate` depends on the corresponding implementation of `imp::Certificate`, it cannot be split separately. But can this status quo be changed?

**Comment by sfackler** [comment]
What is the actual outcome you want to see? Those types have essentially zero functionality outside of plugging into the TLS implementations.

**Comment by delta4chat** [comment]
Unless these types are made into a wrapper type that internally holds the DER format, it's probably not feasible, depending on the author's willingness to do so...

or the external library just needs to convert the certificate stored in DER format to the appropriate type via `Certificate::from_der` first.

No more questions. Close it.
