### ISSUE TITLE
feature = "dummy"

### ISSUE THREAD

**Issue by stepancheg** [sfackler/rust-native-tls#33]
Can rust-native-tls crate have `feature = "dummy"`? When this option is enabled, client code can be compiled with `native_tls` crate, but any call results in error.

Why.

HTTP client or server implementation may have optional TLS. Even if it is enabled, there's runtime switch that enables TLS.

Some people want to avoid compiling OpenSSL (or whateven implementation native-tls uses), because they don't use TLS.

So I need to provide a feature in my library to disable TLS.

Currently I need to have a hundred conditionals in the library code and two builds to verify that code works with and without TLS.

If native-tls crate had an option to effectively disable TLS, I'd just forward that feature flag to `native-tls` crate.

**Comment by sfackler** [comment]
It seems pretty strange that it would take hundreds of conditionals do disable a TLS backend. Maybe some refactoring is in order? There is 1 `#[cfg]` for each TLS backend in rust-postgres for example.

**Comment by stepancheg** [comment]
Well, not hundreds, but tens if you have client and server and dozen of convenient constructors. And you still need to build your code twice: with and without tls just to check you haven't missed something.

Actually, I have two libraries: http/2 and grpc (which depends on http/2), so I need to have these cfg flags in two libraries. 

No-op rusttls would be convenient.

**Comment by sfackler** [comment]
What happens if someone wants to use something other than native-tls?

**Comment by stepancheg** [comment]
Why would someone want to use something other than native tls?

**Comment by sfackler** [comment]
native-tls is not the "one true TLS library". It's targets the "I don't want to do anything particularly exotic and just want this to work with minimal effort". There an enormous swath of functionality you can get using OpenSSL directly instead of native-tls for example.

**Comment by sfackler** [comment]
How can http2 be using this library in the first place? Doesn't http/2 over TLS require ALPN?

**Comment by stepancheg** [comment]
> Doesn't http/2 over TLS require ALPN?

I think it does require ALPN, however, it works without ALPN at least for gRPC.

But why doesn't rust-native-tls support ALPN?

> native-tls is not the "one true TLS library".

Well, it would be good to have "one true TLS library". And I don't have time to invest in implementing abstraction over different TLS implementations. (Especially because I don't understant TLS stuff very vell).

It would be nice if rust-native-tls supported the most important stuff, and I wouldn't use anything it doesn't support. (Actually, I don't know what else besides ALPN I need from TLS library).

**Comment by stepancheg** [comment]
Seems like `Security.framework` doesn't support ALPN. So even if rust-native-tsl supported ALPN, I couldn't use it on OSX for proper implementation of HTTP/2.

So I got another suggestion (which will also make this feature request needless).

Would you like/could you have a crate like `rust-tls-api` with traits

```
trait TslConnector {
    fn connect(...) { ... }
}
trait TlsAcceptor {
    fn accept(...) { ... }
}
trait TlsConnectorBuilder { ... }
trait TlsAcceptorBuilder { ... }
```

and no implementations?

So `rust-openssl`, `rust-schannel` and `rust-security-framework` could depend on that crate and implement these traits?

rust-native-tls could also implement these traits.

So in my implementation of http2/grpc I could simply depend on `rust-tls-api`, have no `#[cfg]` directives at all, and concrete implementation of TLS (or none at all) could be chosen by library user.

**Comment by sfackler** [comment]
Yeah, that'd be a good thing to do.

**Comment by stepancheg** [comment]
Great! What's next? Will you do it all by yourself? Can I help?

**Comment by sfackler** [comment]
I'll start messing around with stuff over the weekend.

**Comment by stepancheg** [comment]
I've created a sketch of implementation: [rust-tls-api](https://github.com/stepancheg/rust-tls-api).

Doesn't work yet, it's empty interfaces and implementation for rust-native-tls in separate crate.

The largest problem I've encountered which I overlooked before is a lack of HKT in Rust. It's not possible to declare:

```
struct TlsConnector {
    type <S> TlsStream<S>;
}
```

So I decided to do it with boxing: `tls_api::TlsStream` is a struct:

```
struct TlsStream(Box<TlsStreamImpl>);
```

Which is probably not a big deal.

**Comment by stepancheg** [comment]
Well, it actually works at least for simple cases:
* [generic test](https://github.com/stepancheg/rust-tls-api/blob/e065279f5e8133df1b41aa7abf7ad10be2c7a01f/api/src/impl_test.rs)
* [executed with rust-native-tls](https://github.com/stepancheg/rust-tls-api/blob/e065279f5e8133df1b41aa7abf7ad10be2c7a01f/native-tls/tests/test.rs)
