### ISSUE TITLE
Allow Backend Customization

### ISSUE THREAD

**Issue by nickbabcock** [sfackler/rust-native-tls#36]
Let's say I've created an openssl [`SslAcceptor`](https://docs.rs/openssl/0.9.12/openssl/ssl/struct.SslAcceptor.html) because I want customizations (initialize from pem format, use mozilla_modern/intermediate, etc). I still want to use this crate's [`TlsAcceptor`](https://docs.rs/native-tls/0.1.2/native_tls/struct.TlsAcceptor.html) because this abstraction is used in higher level crates like [tokio-tls](https://github.com/tokio-rs/tokio-tls) -- and it's a good abstraction. The only problem is that it looks like `rust_native_tls::imp::openssl::TlsAcceptor`, which as far as I know is what I'm looking for, isn't exposed to users.

Is there a way to inject customizations depending on the backend?

**Comment by sfackler** [comment]
There are extension traits for each backend that let you get at the internals. Here are the ones for OpenSSL for example: https://docs.rs/native-tls/0.1.2/native_tls/backend/openssl/index.html.

But if you specifically want to use OpenSSL, why are you using native-tls rather than openssl directly?

**Comment by nickbabcock** [comment]
While I'm using only OpenSSL at the moment, it may change to rustls and using the `TlsAcceptor` struct would simplify integration. Part of the value for this crate is the common interface that `TlsAcceptor` allows.

Take tokio-tls for example, I could write my own implementation of [`TlsAcceptorExt`](https://docs.rs/tokio-tls/0.1.2/tokio_tls/trait.TlsAcceptorExt.html) using `SslAcceptor` directly, but that seems unnecessary because tokio-tls already defines an implementation using `TlsAcceptor` and for the openssl implementation of `TlsAcceptor` only wraps an `SslAcceptor`. I figured I could leverage code already written if I could have `TlsAcceptor` directly instantiated from an `SslAcceptor`.

The reason why I'm not using `TlsAcceptor::builder(<pkcs12>)` is because I use pem, and forcing a conversion to pkcs12 is not ideal.

**Comment by nickbabcock** [comment]
I know bad example -- I was talking hypothetically -- still I find it a possibility that an app, depending on where it is deployed, will want to provide TLS capabilities that don't fall into using pkcs file format and needs cipher suite customization. Maybe this app will use pkcs on osx, pem on linux, and der on windows -- each with a different set of supported cipher suites. This is an odd use case, certainly, but I don't think should be disallowed especially because as far as I can tell, this is possible if all implementations of `TlsAcceptor` are exposed.

**Comment by sfackler** [comment]
Sure - that's why those extension traits exist.

**Comment by nickbabcock** [comment]
Yes, but I can't instantiate either `TlsAcceptorBuilder` or `TlsAcceptor`:

Given:

```rust
use openssl::ssl::{SslMethod, SslAcceptorBuilder, SslAcceptor};
use native_tls::{TlsAcceptor, TlsAcceptorBuilder};
use native_tls::backend::openssl::TlsAcceptorBuilderExt;
// etc

let builder = SslAcceptorBuilder::mozilla_intermediate(SslMethod::tls(), &pkey, &pcert, it)?;
// TlsAcceptorBuilder(builder).build();
// TlsAcceptor(builder.build());
```

Will both fail if either is uncommented with the error.
```
did you mean `TlsAcceptorBuilder { /* fields */ }`?
constructor is not visible here due to private fields
```
And I can't use TlsAcceptor::builder because I don't use pkcs12 🤔 

Am I missing something obvious?

**Comment by sfackler** [comment]
Ah - we should just add a constructor method to `TcpAcceptorExt`.

**Comment by sfackler** [comment]
(The extension traits basically contain whatever people have needed up to now)
