### ISSUE TITLE
Make TlsConnectorBuilder identity take self and return Self

### ISSUE THREAD

**Issue by drager** [sfackler/rust-native-tls#39]
Hey!

I think it's confusing for the [identity function](https://github.com/sfackler/rust-native-tls/blob/872a3781e52bc576e6f3a76c5cee99ea0bf0c7c8/src/imp/openssl.rs#L149) to return a borrowed value. Maybe it should be clearer if identity took self and returned Self?

**Comment by sfackler** [comment]
I may be missing something, but that method returns `()`, not a borrowed value. In any case, non-consuming builders are the preferred approach: https://github.com/brson/rust-api-guidelines#non-consuming-builders-preferred
