### ISSUE TITLE
Allow distrusting system certificate store

### ISSUE THREAD

**Issue by jethrogb** [sfackler/rust-native-tls#41]
Currently when using CA pinning, you always also trust the system certificate store. This is often not wanted.

**Comment by sfackler** [comment]
I believe this'll require a small feature in schannel-rs, but should be straightforward to do.

**Comment by golddranks** [comment]
Any news about this? I'd like to be sure in some situations that I'm only using the one root certificate I've added myself.

**Comment by richardwhiuk** [comment]
We used to be able to do this in native-tls 0.1 with the following code:

```
        let mut ssl =
            openssl::ssl::SslConnectorBuilder::new(openssl::ssl::SslMethod::tls()).unwrap();
        // Server authentication
        ssl.set_ca_file(ca_certificate.clone()).unwrap();
        let builder: native_tls::TlsConnectorBuilder =
            native_tls::backend::openssl::TlsConnectorBuilderExt::from_openssl(ssl);
```

but this method no longer works in nativetls 0.2
