### ISSUE TITLE
about iOS support

### ISSUE THREAD

**Issue by king6cong** [sfackler/rust-native-tls#44]
To enable security-framework working on iOS :  https://github.com/sfackler/rust-native-tls/pull/30

unfortunately, this commit https://github.com/sfackler/rust-native-tls/commit/304b00ee0151b5a2d60dbb491582d5dc40b46587 breaks for iOS because of: 
`use self::security_framework::os::macos::keychain::{self, KeychainSettings};`
which is only available on macOS.

So I created a PR: https://github.com/sfackler/rust-security-framework/pull/41 to make rust-native-tls working on iOS.

There seems a lack of concern for iOS in rust-native-tls, I wonder the status of support for iOS in both rust-native-tls and rust-security-framework. I hope we can make iOS a first-class citizen that is supported.

And I don't know the difference between security-framework on iOS and macOS, but only found a macOS module here: https://github.com/sfackler/rust-security-framework/tree/master/security-framework/src/os

Thanks 😃

**Comment by azdlowry** [comment]
We are currently using rust-native-tls on ios through our own fork, as it's pretty important to us that this continues to work so we don't have to use OpenSSL and argue with the app store.

The biggest difference between ios and macos seems to be is the lack of keychain support in ios. (See: https://github.com/azdlowry/rust-native-tls/commit/a0a3967e576265ad685e3015aa60b1ad750cd6e4)

**Comment by sfackler** [comment]
As I said on #30, I'd be happy to support iOS, but that needs to include CI testing on Travis.

**Comment by azdlowry** [comment]
I've managed to get cargo build to work with an ios target through travis. Running the tests will be a bit harder, but it's a start.

**Comment by azdlowry** [comment]
I now have the tests running on the ios simulator from travis.  See https://github.com/azdlowry/rust-native-tls.

It's not the prettiest solution, as it uses https://github.com/SSheldon/rust-test-ios which has some issues, but it's a start. I can submit a PR if your happy with this approach?

**Comment by sfackler** [comment]
Yes, please do!

**Comment by azdlowry** [comment]
#50 Added ios support and and ios ci.
