### ISSUE TITLE
2 variables "stream"

### ISSUE THREAD

**Issue by GildedHonour** [sfackler/rust-native-tls#47]
```
    let connector = TlsConnector::builder().unwrap().build().unwrap();

    let stream = TcpStream::connect("google.com:443").unwrap();
    let mut stream = connector.connect("google.com", stream).unwrap();

    stream.write_all(b"GET / HTTP/1.0\r\n\r\n").unwrap();
```

why stream 2 times, what's that supposed to mean?

**Comment by sfackler** [comment]
The example just happens to choose that name for both values. It's exactly the same as

```rust
    let connector = TlsConnector::builder().unwrap().build().unwrap();

    let stream = TcpStream::connect("google.com:443").unwrap();
    let mut tls_stream = connector.connect("google.com", stream).unwrap();

    tls_stream.write_all(b"GET / HTTP/1.0\r\n\r\n").unwrap();
```

**Comment by GildedHonour** [comment]
Ok
The host is specified 2 times, is it possible to avoid that? 

Can they be different and if so, in what case? For example
```
    let stream = TcpStream::connect("google.com:443").unwrap();
    let mut tls_stream = connector.connect("something_else.com", stream).unwrap();
```

**Comment by sfackler** [comment]
The first usage connects to the server and the second is used to validate the server's certificate. If you set the second to something else it'll fail to connect.

**Comment by GildedHonour** [comment]
If they're always the same, why have a function which requires it as a parameter? I can create a PR fixing this.

**Comment by sfackler** [comment]
How would you avoid that?

**Comment by GildedHonour** [comment]
stream.peer_addr() or stream.local_addr()

**Comment by sfackler** [comment]
Those provide the IP address of the peer, which is not what is required. Certificate validation requires the hostname.
