### ISSUE TITLE
ALPN support

### ISSUE THREAD

**Issue by alexcrichton** [sfackler/rust-native-tls#49]
At the recent all-hands we discussed TLS-in-Rust a bit and one of the nice features to add to this library would be ALPN support, especially in support of HTTP/2. For the backends native-tls has:

* `openssl` crate already has ALPN support
* `security-framework` does not have ALPN support. This may be available in the upcoming high sierra OSX though? And this may be available through private APIs in historical releases of OSX? It may be possible to write a shim that works with all this.
* `schannel` doesn't have ALPN support but it's suspected that it does indeed exist in Windows, we just need to bind it.

**Comment by hinaria** [comment]
hi alex,

here are some notes on using alpn via schannel. hope this helps:

- alpn is indeed available in schannel, but only on windows 8.1 and later. computers running windows 8, windows 7 and windows xp can't use schannel alpn.
- specify alpn protocols by passing a [`SecBuffer { buffer-type = SECBUFFER_APPLICATION_PROTOCOLS }`][1] to [`fn InitializeSecurityContext()`][2].
- query the requested alpn protocols using [`QueryContextAttributes(attribute: SECPKG_ATTR_APPLICATION_PROTOCOL, ...)`][3].

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/aa379814(v=vs.85).aspx
[2]: https://msdn.microsoft.com/en-us/library/windows/desktop/aa375924(v=vs.85).aspx
[3]: https://msdn.microsoft.com/en-us/library/windows/desktop/aa379340(v=vs.85).aspx

**Comment by ePirat** [comment]
> This may be available in the upcoming high sierra OSX though?
It was promised to be in High Sierra but so far the Security framework does not export the symbols even though the functions are publicly documented. There is a radar filed with Apple about that already.

> And this may be available through private APIs in historical releases of OSX?
Yes there is a private API that could be used since macOS 10.11

**Comment by sfackler** [comment]
ALPN has finally landed in OSX 10.13.4. Unfortunately, it only implements the client side and not the server side so that's all we'd be able to support here.

**Comment by michaelbeaumont** [comment]
Hi, what's the status of this issue? I'm updating a library from 0.1 and I'm stuck now that `backend` was removed (https://github.com/sfackler/rust-native-tls/issues/103). I was downcasting to `openssl` in order to do ALPN negotiation.

**Comment by est31** [comment]
@michaelbeaumont there is a PR for schannel but it seems quite dead: https://github.com/steffengy/schannel-rs/pull/49

**Comment by Eroc33** [comment]
@est31 My PR should hopefully be in a useable state now

**Comment by coltfred** [comment]
Anyone have a status update on this? I'm highly interested in http2 support

**Comment by LuoZijun** [comment]
`schannel` ALPN support: https://github.com/steffengy/schannel-rs/pull/68

**Comment by zonyitoo** [comment]
ALPN support for schannel has already released.

**Comment by est31** [comment]
See https://github.com/sfackler/rust-native-tls/pull/157

**Comment by MarnixKuijs** [comment]
As of now there are 2 pull request open for this issue #157 and #165, but neither seems to be making progress. I would like this ALPN support very much, but it seems that neither PR is making any progress. If possible I would like to take over from @LuoZijun or @cyan1. Probably also best if we make a choice about which PR we will continue with.
