### ISSUE TITLE
Certificates from .pem

### ISSUE THREAD

**Issue by nindalf** [sfackler/rust-native-tls#53]
X509 certificates can currently be created using the function `x509::X509::from_der()`. I propose adding a similar method to create an X509 certificate from a `.pem` file. 

I would be willing to submit a PR for this functionality, if someone could give me a little direction on which way to proceed.

I think we would use [`this method`](https://docs.rs/openssl/0.9.15/openssl/x509/struct.X509.html#method.from_pem) from the openssl crate. However, the current code in rust-native-tls uses rust-security-framework, which uses the native macOS stack in preference to openssl. 

My questions are 

1. Is this functionality something that is desirable in rust-native-tls, from your perspective?
1. Which code path is invoked on non-macOS platforms? Which of these need to be changed?

Thanks

Krishna

**Comment by sfackler** [comment]
Yep, this is definitely something that we should support! It'd use https://docs.rs/schannel/0.1.7/i686-pc-windows-gnu/schannel/cert_context/struct.CertContext.html#method.from_pem on Windows, https://github.com/sfackler/rust-security-framework/blob/master/security-framework/src/os/macos/import_export.rs#L43 on OSX, and the method you found on OpenSSL.

**Comment by nindalf** [comment]
Thanks Steve, I'll update this thread if I have any issues implementing it.

**Comment by dbrgn** [comment]
I would very much like to see this! Did you make any progress, @nindalf?

**Comment by nindalf** [comment]
@dbrgn I did. I hope to get something up soon.

**Comment by sfackler** [comment]
This is now implemented.
