### ISSUE TITLE
Could Certificate be clonable?

### ISSUE THREAD

**Issue by golddranks** [sfackler/rust-native-tls#55]
If I need to set up multiple connectors that all use the same CA certificate that I provide, it feels icky to parse the certificate from a .der file over and over again. I don't know the insides of the `Certificate`, but I think that if it could, it should implement `Clone`.

**Comment by sfackler** [comment]
All of the underlying implementation libraries have clonable certificates, so this should be pretty straightforward/reasonable to implement.

**Comment by mmstick** [comment]
Could also use this feature in my [Concurr](https://github.com/mmstick/concurr) application.
