### ISSUE TITLE
Linux KTLS Support

### ISSUE THREAD

**Issue by quininer** [sfackler/rust-native-tls#57]
Linux 4.13 added [TLS support](https://github.com/torvalds/linux/blob/master/Documentation/networking/tls.txt) in the kernel, which is really native tls that support it makes sense.

:)

**Comment by sfackler** [comment]
First step would be a library wrapping it.

**Comment by quininer** [comment]
KTLS currently only handles symmetric encryption, so we still need a TLS library for handshake.

**Comment by baloo** [comment]
Openssl3 brings transparent ktls support. No changes are needed here.
