### ISSUE TITLE
invalid purpose

### ISSUE THREAD

**Issue by mikedilger** [sfackler/rust-native-tls#58]
When using NativeTLS for STARTTLS within SMTP, I've been getting OpenSSL "certificate validation failed" errors from well known mail servers (like gmail, outlook, and fastmail).  See https://github.com/lettre/lettre/issues/198. Is it possible that NativeTLS is using OpenSSL in a way that presumes the purpose such that SMTP/STARTTLS would not validate?

**Comment by sfackler** [comment]
What's the exact error message being returned out of OpenSSL?

It sounds like it doesn't like the certificate's configured `keyUsage` settings. From a quick read of the STARTTLS standard it doesn't seem like anything should be different there. It might be helpful to track down the certificate OpenSSL's not happy with to see what's going on with it.

**Comment by mikedilger** [comment]
I agree, it sounds like key usage.  1.0.2g gives the code 336134278 which seems to break down to (looking at the OpenSSL source for that branch) "Renegotation Encoding Error": "Certificate Verify Failed": "Invalid Purpose".  I don't recall 1.1.0 outputting a code in the error message, but it did say "certificate verify failed".

I tried from several computers in different data centres, in case some "smart" router thought it would be smart to play MitM in order to filter outbound spam.

I find it suprising, though, that this error happens on every SMTP server I have tried:
* gmail-smtp-in.l.google.com
* in1-smtp.messagingengine.com
* decodeit-co-nz.mail.protection.outlook.com

I really want to inspect the certificates to see what is going on.  Do you have suggestions for how to extract/debug the certificates?  #48 would be nice.

**Comment by sfackler** [comment]
Wireshark might be the easiest option.

**Comment by mikedilger** [comment]
Ok, I'll get into it within the next few days, possibly submit a PR.  Thanks.

**Comment by mikedilger** [comment]
The problem was that I was leaving a dot at the end of the domain name.   I'm not sure why the OpenSSL error seemed to be 'invalid purpose', but worked fine once I found and removed the dot.
