### ISSUE TITLE
[Question] confused about HandshakeError::Interrupted

### ISSUE THREAD

**Issue by osa1** [sfackler/rust-native-tls#59]
Sorry this is not really an issue but a question..

I'm trying to understand how to use `native-tls` with non-blocking sockets (more specifically, `TcpStream`). `TlsConnector::connect` returns `HandshakeError::Interrupted`, but it doesn't say what it needs to do, reading or writing. So I'm not sure what signal to wait for (i.e. readiness event).

Assuming I'm not the only one it may be a good idea to add a word or two about this in the documentation..

Thanks..

**Comment by sfackler** [comment]
The best option I'm aware of is to wrap the `TcpStream` in something that records if the last operation was a read or write.

**Comment by osa1** [comment]
Thanks.. Do you know any code that does this? It would be good to take a peek..

**Comment by sfackler** [comment]
All of the current nonblocking code I'm aware of uses Tokio, which manages this internally. You might be able to look back in the history of the async Hyper work - back before it switched over to Tokio it did something like this.

**Comment by osa1** [comment]
Alright -- thanks for the pointers. Closing.
