### ISSUE TITLE
Support LibreSSL

### ISSUE THREAD

**Issue by lambda** [sfackler/rust-native-tls#60]
There are some distros which do not have packages for OpenSSL at all, but which do provide LibreSSL. [LibreSSL](http://www.libressl.org/) is a fork of OpenSSL in which much legacy code has been removed and which has been reorganized to be easier to maintain. According to [this Reddit thread](https://www.reddit.com/r/rust/comments/7ceihp/tiny_030_released_now_supports_ipv6_and_tls/dpplds6/) some versions of LibreSSL would work due to some amount of compatibility with OpenSSL, but that is not guaranteed.

Since it looks like LibreSSL is the "native tls" on certain platforms, like [Void Linux](https://www.voidlinux.eu/), it would probably be useful to explicitly support and test it.

Alternatively, providing a "non-native TLS" option, like [rustls](https://github.com/ctz/rustls) might make it possible for users who don't have any of the native TLS options to use projects that depend on this, without having to have each downstream project add support for two different TLS crates.

**Comment by lambda** [comment]
See osa1/tiny#37 for the downstream issue.

**Comment by sfackler** [comment]
rust-openssl already supports LibreSSL.

**Comment by lambda** [comment]
Ah, maybe filed issue against the wrong repo then. Probably better for the person with the original issue to file a more detailed issue against `rust-openssl`.
