### ISSUE TITLE
No way to detect connection closure on the remote side?

### ISSUE THREAD

**Issue by osa1** [sfackler/rust-native-tls#61]
I'm reading `std::io::Read` and `native_tls::TlsStream` documentation and I'm confused about detecting connection closure on the remote side.

It seems to me that I can't rely on `read()` return value being `Ok(0)` to consider that the connection is closed, because it may be possible that bytes were read but they were used for maintaining the TLS stream rather than the the actual data sent by the remote process using the TLS stream. In which case `read()` would return `Ok(0)` because the documentation says `n <= buf.len()` should hold, and buf won't be filled at all because received data is used for maintaining the TLS stream.

If this is true, then there's no way to detect when a connection is closed on the remote side using `TlsStream`.

Arguably, `Read`s design is not great here. Because of `n <= buf.len()` invariant `read()` can't report "data received but used to maintain the underlying stream" (e.g. TLS lifecycle).

Am I missing anything? Would it be possible to add another method to `TlsStream` for checking if the connection is closed? (of course this would only work if the underlying stream returns `Ok(0)` in this case which is not always the case but works with `TcpStream`)

**Comment by sfackler** [comment]
A single call to `TlsStream::read` will do an arbitrarily large number of reads and writes on the underlying socket, but won't return until it's reached EOF (either because the underlying socket is closed, or because the TLS session is closed), or until there's some amount of data ready to copy into the buffer.

**Comment by osa1** [comment]
> won't return until it's reached EOF (either because the underlying socket is closed, or because the TLS session is closed), or until there's some amount of data ready to copy into the buffer

How is that even possible to implement? I'm using a non-blocking `TcpStream`, so `TlsStream` can't block until there's enough data in the socket to read and fill the buffer. What am I missing?

**Comment by sfackler** [comment]
If the underlying stream reports an error (e.g. if there's no data available and the socket's in nonblocking mode), `TlsStream` returns that error, and the caller will call read again when there's data available.

**Comment by osa1** [comment]
Let me try to explain in different words.

Suppose I have `TlsStream<SomeOtherStream>`.

`SomeOtherStream`'s `read()` never blocks.

Suppose that the program only uses `TlsStream<SomeOtherStream>`.

If there's `N` bytes in the `SomeOtherStream` buffer, `TlsStream` can return `M` bytes such that `M <= N`.

So it's possible that `SomeOtherStream` receives 10 bytes but `TlsStream::read` returns 5 bytes.

Am I correct so far?

Now suppose that `SomeOtherStream` received 5 bytes. I call `TlsStream::read`.

Now it should be possible that this call returns `Ok(0)` even though the stream is not closed.

So there should be a way to distinguish these two cases:

1. 0 bytes returned but not because the stream is closed, it's just that the received contents used to maintain TLS connection
2. 0 bytes returned because the stream is closed

**Comment by sfackler** [comment]
> Now it should be possible that this call returns Ok(0) even though the stream is not closed.

No, that is not possible.
