### ISSUE TITLE
How to check if `native_tls::Error` caused by WouldBlock?

### ISSUE THREAD

**Issue by osa1** [sfackler/rust-native-tls#63]
In a `native_tls` application we're getting an error with description "The underlying stream reported an error" and cause description "operation would block". Looking at the source code, it seems like we're hitting https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/error.rs#L48 . I need to somehow check for this case and but `native_tls` abstracts over TLS library error types and as far as I can see it's not currently possible to check if a `native_tls::Error` is caused by a `WouldBlock` error.

I'm wondering if it's there's a way to do that that I'm missing, or if it makes sense to add such a method to `native_tls::Error`. Any ideas?

**Comment by sfackler** [comment]
Which method in particular do you think you need to do that check for? tokio-tls, for example, doesn't need to do that: https://github.com/tokio-rs/tokio-tls/blob/master/src/lib.rs

**Comment by osa1** [comment]
Sorry for late response,

It's interesting that tokio-tls doesn't need that. It may be because:

- They use an underlying stream type that handles `EWOULDBLOCK`s correctly (in our case we use https://github.com/osa1/tiny/blob/master/src/stream/tcp.rs).
- Their implementation is also broken. I recently discovered that if I use 1.0.2g (dynamically linked) my code works fine. If I use 1.1.0g (statically linked) it doesn't. (tracking issue https://github.com/osa1/tiny/issues/64)

My original request was a function of type `fn(native_tls::Error) -> bool` that checks if the error is caused by `EWOULDBLOCK`, but this may not be necessary when the underlying stream implemented correctly. I'll try to see if there's a problem with our `TcpStream` implementation.

**Comment by osa1** [comment]
Closing this as I no longer need this.
