### ISSUE TITLE
Couldn't add root certificate on ubuntu

### ISSUE THREAD

**Issue by tekjar** [sfackler/rust-native-tls#66]
Hi. `add_root_certificate(ca)` method call is working on mac but not on linux. It's failing with this error

```
ErrorStack([Error { code: 185057381, library: "x509 certificate routines", function: "X509_STORE_add_cert", reason: "cert already in hash table", file: "x509_lu.c", line: 361
```

**Comment by sfackler** [comment]
It looks like the certificate is already trusted. Are you sure you need to
add it at all?
