### ISSUE TITLE
Library has no ciphers

### ISSUE THREAD

**Issue by pgab** [sfackler/rust-native-tls#71]
I am trying to connect to a server with a self signed certificate. Whilst doing so from a C++/Qt application everything works as expected. I can connect to the server and call several functions.

I use the same API from a Apache2.4/PHP5.6 backend. When I try to simply connect to the same server using the same certificate on the client side I always get
`The OpenSSL library reported an error: error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers:../ssl/ssl_lib.c:2519:`

Additoinally: everything runs on the same host: the application server, the C++/Qt application and the Apache2.4/PHP5.6 backend.

I have read that calling `SSL_library_init(); ` might help, but from my point of view we are not even able to call this method. I also couldn't find an equivalent in openssl* functions in PHP.

**Comment by sfackler** [comment]
My guess is that you're building against OpenSSL 1.1.0 and running against OpenSSL 1.0.2 or 1.0.1. Are you statically or dynamically linking to it?

**Comment by pgab** [comment]
Indeed it is linked dynamically. So that different versions might come from different dependencies.

I just checked that on a different system and it seems to have the as well libssl.so.1.1 and libssl.so.1.0.0 as dependency and even loaded and it seems to work fine. Is this probably more by accident?

**Comment by pgab** [comment]
I just rebuild the complete stack and it seems to work properly now.
