### ISSUE TITLE
How to deserialize Pkcs12 from openssl::Pkcs12's serialization?

### ISSUE THREAD

**Issue by danneu** [sfackler/rust-native-tls#78]
I have TLS working on my server where I've built a Pkcs12 (.pfx) file from the key/cert generated by Let's Encrypt. That works fine.

But now I also want my server to be able to generate its own signed cert in memory on server boot. I use rust-openssl to generate a key/cert pair and then DER-serialize it in memory, but I'm having trouble deserializing it to native_tls::Pkcs12 so that I can initialize my serve with it.

- I'm on OSX.
- I took the key/cert generation in `generate_pair()` from the docs' example. Ideally I would change it so that it uses the same parameters as CLI openssl's keygen, but I'm still researching that.
- Why doesn't `openssl::Pkcs12::from_der()` take a password as an argument? It decodes the archive without one.

Anyways, this snippet demonstrates that native_tls is unable to deserialize the pfx file that rust-openssl generated.

Alternatively, is there a better solution for get the server to generate and use its own self-signed cert?

```rust
extern crate native_tls;
extern crate openssl;

use openssl::x509::{self, X509, X509Name, X509Ref};
use openssl::pkey::{PKey, PKeyRef};
use openssl::hash::MessageDigest;
use openssl::rsa::Rsa;

use openssl::pkcs12::Pkcs12Builder;
use openssl::pkcs12::Pkcs12;

// Generates a key/cert pair
fn generate_pair() -> (PKey, x509::X509) {
    let rsa = Rsa::generate(2048).unwrap();
    let key = PKey::from_rsa(rsa).unwrap();

    let mut name = X509Name::builder().unwrap();
    name.append_entry_by_nid(openssl::nid::COMMONNAME, "example.com").unwrap();
    let name = name.build();

    let mut builder = X509::builder().unwrap();
    builder.set_version(2).unwrap();
    builder.set_subject_name(&name).unwrap();
    builder.set_issuer_name(&name).unwrap();
    builder.set_pubkey(&key).unwrap();
    builder.sign(&key, MessageDigest::sha256()).unwrap();

    let cert: openssl::x509::X509 = builder.build();
    
    (key, cert)
}

fn main() {
    let (key, cert) = generate_pair();

    // Let's turn out key/cert pair into a pkcs12 archive with a password of "secret"
    const PASSWORD: &str = "secret";

    let pkcs12 = openssl::pkcs12::Pkcs12::builder()
        .build(password, "friendly_name", &*key, &cert)
        .unwrap();

    // The DER-encoded bytes of the archive
    let der = pkcs12.to_der().unwrap();

    // openssl's Pkcs12 struct can deserialize the round-trip.
    let pkcs12 = openssl::pkcs12::Pkcs12::from_der(&der).unwrap();

    // But native_tls' Pkcs12 cannot.
    let native_tls_pfx = native_tls::Pkcs12::from_der(&der, PASSWORD).unwrap();
    // (Fails)
}
```

On OSX, the error is:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -25257, message: "Unknown format in import." }'
```

On Linux, the error is:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Ssl(ErrorStack([Error { code: 218570907, library: "asn1 encoding routines", function: "ASN1_get_object", reason: "too long", file: "asn1_lib.c", line: 147 }, Error { code: 218529894, library: "asn1 encoding routines", function: "ASN1_CHECK_TLEN", reason: "bad object header", file: "tasn_dec.c", line: 1185 }, Error { code: 218595386, library: "asn1 encoding routines", function: "ASN1_ITEM_EX_D2I", reason: "nested asn1 error", file: "tasn_dec.c", line: 219, data: "Type=ASN1_TIME" }, Error { code: 218640442, library: "asn1 encoding routines", function: "ASN1_TEMPLATE_NOEXP_D2I", reason: "nested asn1 error", file: "tasn_dec.c", line: 697, data: "Field=notBefore, Type=X509_VAL" }, Error { code: 218640442, library: "asn1 encoding routines", function: "ASN1_TEMPLATE_NOEXP_D2I", reason: "nested asn1 error", file: "tasn_dec.c", line: 697, data: "Field=validity, Type=X509_CINF" }, Error { code: 218640442, library: "asn1 encoding routines", function: "ASN1_TEMPLATE_NOEXP_D2I", reason: "nested asn1 error", file: "tasn_dec.c", line: 697, data: "Field=cert_info, Type=X509" }, Error { code: 218919022, library: "asn1 encoding routines", function: "ASN1_item_unpack", reason: "decode error", file: "asn_pack.c", line: 205 }, Error { code: 587686002, library: "PKCS12 routines", function: "PKCS12_parse", reason: "parse error", file: "p12_kiss.c", line: 132 }]))', /checkout/src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sfackler** [comment]
> Why doesn't openssl::Pkcs12::from_der() take a password as an argument? It decodes the archive without one.

The password is provided when you extract values from the archive: https://docs.rs/openssl/0.10.5/openssl/pkcs12/struct.Pkcs12.html#method.parse

The native_tls call combines those two calls which is why one is succeeding and the other isn't.

It may be failing to parse because the X509 certificate isn't valid. It's missing notBefore and notAfter entries, etc.

**Comment by danneu** [comment]
@sfackler Wow... thanks! You were right. I just had to set notBefore/notAfter. I don't think I would've figured that out myself for some time.

I don't have the energy for it at the moment, but it'd definitely be nice to sometime add these lines to the x509 example https://docs.rs/openssl/0.10.5/openssl/x509/index.html#example:

```rust
use openssl::asn1::Asn1Time;

// ...
builder.set_not_before(&Asn1Time::days_from_now(0).unwrap());
builder.set_not_after(&Asn1Time::days_from_now(7).unwrap());
```

**Comment by sfackler** [comment]
That example's been removed: https://github.com/sfackler/rust-openssl/commit/f645165ee2b41f9c15d9a7d8f3eec56000b7e445. X509 is complex enough that people shouldn't really be trying to construct certificates manually unless they already know what they're doing.

**Comment by danneu** [comment]
Agreed. I would've never had an issue had I remembered to look for an examples directory. That's a great demo.

Thanks again.
