### ISSUE TITLE
Automatically run openssl-probe?

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-native-tls#82]
The location of the trust root isn't consistent across distributions. A distro's own OpenSSL is configured to look in the right place but if you're statically linking to make a portable binary things aren't going to automatically work. You can use [openssl-probe](https://docs.rs/openssl-probe/0.1.2/openssl_probe/) to track down the right location but that isn't done automatically in native-tls right now.

We could unconditionally run it but it seems like it could produce some weird behavior when you *are* dynamically linking to the system OpenSSL. We could maybe make it a Cargo feature or a function you can call optionally?

cc @jwilm

**Comment by golddranks** [comment]
I think that might have made things "just work" for me, re: https://github.com/rusoto/rusoto/issues/1049
