### ISSUE TITLE
Add support for construction TlsStream from raw stream

### ISSUE THREAD

**Issue by Xudong-Huang** [sfackler/rust-native-tls#88]
Is it possible to add a function to convert a raw stream into a `TlsStream` without performing a handshake.
Since TlsStream is not clone, we can use something like `from_raw()` to convert an already established connection to a `TlsStream`. 

Thanks.

**Comment by sfackler** [comment]
How would this be implemented with e.g. the OpenSSL backend?

**Comment by sfackler** [comment]
A TlsStream is stateful - you can't just make two of them that both talk to the same socket.

**Comment by Xudong-Huang** [comment]
This make sense. Thank you!
