### ISSUE TITLE
Would it be possible to support TlsStream<TcpStream>::try_clone?

### ISSUE THREAD

**Issue by emk** [sfackler/rust-native-tls#89]
Hello! At Faraday, we've been using `native-tls` in a number of applications, and we're very happy with it. We've been working on a pull request for the Rust `amqp` crate which would switch it from using OpenSSL to `native-tls`.

However, in one critical place, `amqp` relies on `TcpStream::try_clone()`, or the OpenSSL equivalent. It would probably require an overhaul to avoid this. In particular, we need to be able to send writes while another thread waits on reads.

I notice that there is no `try_clone` method or equivalent for `TlsStream<TcpStream>`. Is this because of Windows or Mac portability restrictions? How much work would it take to implement this? We're happy to spend some time working on a PR, but we figured we should ask first. :-)

Thank you for any advice you can provide, and for `native-tls`!

**Comment by sfackler** [comment]
It is not possible to implement try_clone on any backend. A TLS stream is inherently stateful.

**Comment by emk** [comment]
Interesting!

It turns out that `rust-amqp` was definitely calling `try_clone` on an OpenSSL `SslStream<TcpStream>`, [as provided here by `openssl`](https://docs.rs/openssl/0.7.14/openssl/ssl/struct.SslStream.html#method.try_clone).

The documentation for `try_clone`, however, reads:

> **Deprecated**
>
> This method does not behave as expected and will be removed in a future release.

So it looks like `rust-amqp` is actually relying on incorrect and non-portable OpenSSL behavior that has been removed in newer releases. And unfortunately, this seems to be pretty deeply baked into the code, because it tries to listen for inbound messages while still allowing outbound messages—it's treating the connection as two independent one-way connections.

Now I need to find a solution elsewhere, and it looks like this is going to be trickier than I had hoped. :-(

Thank you for helping me get to the bottom of this!
